"""Strictly local OrcaSlicer invocation and deterministic G-code normalization."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from . import spec

APPIMAGE_SHA256 = "e1a07275a25f176626c55a5df39e91bc4476d8c28ee4a3192ff758e29dd5c3ba"
PROFILE_HASHES = {
    "machine": "5433a5ab8ff3e31deba7228185c2aca1bc9c97e42a6c8ed1e390df58f8a0eccd",
    "filament": "98de4434a4aa6afeda112b3ee621866c57f24ae7a1d7c20b4307a9e541fe5d35",
    "process": "ffc026a9c0db3985928c2291aa9a95bd2fac3e5324c3c6b3deaa45f5f4d07dd2",
}


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def find_slicer_root(explicit: Path | None = None) -> Path:
    candidates: list[Path] = []
    if explicit is not None:
        candidates.append(explicit)
    if os.environ.get("ORCA_SLICER_ROOT"):
        candidates.append(Path(os.environ["ORCA_SLICER_ROOT"]))
    repository = Path(__file__).resolve().parents[2]
    candidates.extend(
        [
            repository / ".tools" / "orca" / "squashfs-root",
            Path("/tmp/braille-card-tools/squashfs-root"),
        ]
    )
    for root in candidates:
        if (root / "bin/orca-slicer").is_file() and (root / "libexec/orca-slicer-env").is_file():
            return root.resolve()
    raise FileNotFoundError(
        "OrcaSlicer 2.4.2 extracted root not found; run tools/bootstrap_orca.sh "
        "or pass --slicer-root"
    )


def _stock_paths(root: Path) -> dict[str, Path]:
    sovol = root / "resources/profiles/Sovol"
    return {
        "machine": sovol / "machine/Sovol SV07 0.4 nozzle.json",
        "filament": sovol / "filament/Sovol SV07 PLA.json",
        "process": sovol / "process/0.20mm Standard @Sovol SV07.json",
    }


def verify_stock_profiles(root: Path) -> dict[str, Path]:
    paths = _stock_paths(root)
    for name, path in paths.items():
        if not path.is_file():
            raise FileNotFoundError(f"Missing stock OrcaSlicer profile: {name}")
        actual = sha256_file(path)
        if actual != PROFILE_HASHES[name]:
            raise ValueError(f"Unexpected {name} profile SHA-256: {actual}")
    return paths


def _write_json(path: Path, payload: dict[str, object]) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def _merged_profiles(stock: dict[str, Path], temp_dir: Path) -> dict[str, Path]:
    machine = json.loads(stock["machine"].read_text(encoding="utf-8"))
    machine["default_bed_type"] = "Textured PEI Plate"

    filament = json.loads(stock["filament"].read_text(encoding="utf-8"))
    # The stock SV07 PLA profile's hot-plate value is 65 °C. Orca's CLI has no
    # plate selector, so pin every candidate plate field to that same stock
    # value; this prevents a GUI default from silently selecting 35 °C.
    for key in (
        "cool_plate_temp", "cool_plate_temp_initial_layer",
        "eng_plate_temp", "eng_plate_temp_initial_layer",
        "hot_plate_temp", "hot_plate_temp_initial_layer",
        "textured_plate_temp", "textured_plate_temp_initial_layer",
        "supertack_plate_temp", "supertack_plate_temp_initial_layer",
    ):
        filament[key] = ["65"]

    process = json.loads(stock["process"].read_text(encoding="utf-8"))
    override_path = Path(__file__).resolve().parents[2] / "profiles/reference_card_process_overrides.json"
    overrides = json.loads(override_path.read_text(encoding="utf-8"))
    for key, value in overrides.items():
        if key not in {"type", "name", "from", "inherits"}:
            process[key] = value
    process["name"] = "Braille reference card @Sovol SV07"
    process["inherits"] = "fdm_process_common"

    outputs = {
        "machine": temp_dir / "machine.json",
        "filament": temp_dir / "filament.json",
        "process": temp_dir / "process.json",
    }
    _write_json(outputs["machine"], machine)
    _write_json(outputs["filament"], filament)
    _write_json(outputs["process"], process)
    return outputs


def normalize_gcode(raw: bytes) -> bytes:
    """Normalize the sole wall-clock field while preserving executable G-code."""
    text = raw.decode("utf-8")
    text, count = re.subn(
        r"^; generated by OrcaSlicer 2\.4\.2 on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$",
        "; generated by OrcaSlicer 2.4.2; timestamp normalized to deterministic text",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError("Expected OrcaSlicer timestamp header was not found exactly once")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    return text.encode("utf-8")


def validate_gcode(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    required = {
        "slicer": "; generated by OrcaSlicer 2.4.2; timestamp normalized",
        "machine": "; printer_model = Sovol SV07",
        "bed": "; bed_shape = 0x0,220x0,220x220,0x220",
        "nozzle": "; nozzle_diameter = 0.4",
        "material": "; filament_type = PLA",
        "supports": "; enable_support = 1",
        "support_type": "; support_type = tree(auto)",
        "layer_height": "; layer_height = 0.2",
        "initial_bed_temperature": "M140 S65",
        "initial_nozzle_temperature": "M104 S235",
        "end_macro": "END_PRINT",
    }
    missing = [name for name, marker in required.items() if marker not in text]
    if missing:
        raise ValueError("G-code validation missing: " + ", ".join(missing))
    if re.search(r"generated by OrcaSlicer .* on \d{4}-\d{2}-\d{2}", text):
        raise ValueError("G-code retains a wall-clock timestamp")
    layer_count = text.count(";LAYER_CHANGE")
    if layer_count < 800:
        raise ValueError(f"Unexpectedly low upright layer count: {layer_count}")
    return {
        "validated": True,
        "layer_count": layer_count,
        "supports_enabled": True,
        "initial_bed_temperature_c": 65,
        "initial_nozzle_temperature_c": 235,
        "normal_nozzle_temperature_c": 200,
        "submitted_to_printer": False,
    }


def slice_card(stl_path: Path, output: Path, slicer_root: Path | None = None) -> dict[str, object]:
    """Slice one local STL. This function has no upload or printer-control path."""
    root = find_slicer_root(slicer_root)
    stock = verify_stock_profiles(root)
    with tempfile.TemporaryDirectory(prefix="braille-card-slice-") as temp_name:
        temp_dir = Path(temp_name)
        profiles = _merged_profiles(stock, temp_dir)
        shutil.copyfile(stl_path, temp_dir / "card.stl")
        (temp_dir / "out").mkdir()
        (temp_dir / "data").mkdir()
        command = [
            str(root / "libexec/orca-slicer-env"),
            str(root / "bin/orca-slicer"),
            "--debug", "2",
            "--datadir", "data",
            "--load-settings", "machine.json;process.json",
            "--load-filaments", "filament.json",
            "--slice", "0",
            "--outputdir", "out",
            "card.stl",
        ]
        completed = subprocess.run(
            command,
            cwd=temp_dir,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env={**os.environ, "LC_ALL": "C", "TZ": "UTC"},
        )
        if completed.returncode != 0:
            error = completed.stderr.decode("utf-8", errors="replace").strip()
            raise RuntimeError(f"OrcaSlicer failed with code {completed.returncode}: {error}")
        candidates = sorted((temp_dir / "out").glob("*.gcode"))
        if len(candidates) != 1:
            raise RuntimeError(f"Expected one sliced G-code file, found {len(candidates)}")
        output.write_bytes(normalize_gcode(candidates[0].read_bytes()))
    summary = validate_gcode(output)
    summary.update(
        {
            "slicer": f"OrcaSlicer {spec.ORCA_SLICER_VERSION}",
            "machine_profile": spec.SV07_PROFILE_NAME,
            "filament_profile": spec.SV07_FILAMENT_PROFILE,
            "process_profile": spec.SV07_PROCESS_PROFILE,
            "stock_profile_sha256": PROFILE_HASHES,
            "gcode_sha256": sha256_file(output),
        }
    )
    return summary

