"""UEB translation checks against examples independent of liblouis.

Authoritative source: Australian Braille Authority, *Unified English Braille:
Australian Training Manual*, revised January 2022, Unicode edition.
https://pqa.oni.mybluehost.me/wp-content/uploads/2013/10/UEB-Australian-Training-Manual-January-2022-Unicode.pdf

Lesson 1, print pages 15–17 (PDF pages 15–17): alphabet, capital indicator,
full stop, and numeric examples. In particular, the manual prints the exact
pairs Dad → ⠠⠙⠁⠙, Big Cage → ⠠⠃⠊⠛⠀⠠⠉⠁⠛⠑, and
206 → ⠼⠃⠚⠋. These expected strings were transcribed from that publication,
not generated by liblouis.
"""

from braille_card.braille import REVIEW_STATUS, translate


def test_authoritative_ueb_grade1_pairs() -> None:
    known_good = {
        "Dad": "⠠⠙⠁⠙",
        "Big Cage": "⠠⠃⠊⠛⠀⠠⠉⠁⠛⠑",
        "206": "⠼⠃⠚⠋",
    }
    for source, expected in known_good.items():
        assert translate(source).unicode == expected


def test_translation_is_explicitly_unreviewed() -> None:
    translated = translate("With love")
    assert translated.grade == "UEB Grade 1 (uncontracted)"
    assert translated.table == "en-ueb-g1.ctb"
    assert translated.review_status == REVIEW_STATUS == "not yet human-reviewed"

