from __future__ import annotations

import re
import socket
from pathlib import Path

from braille_card.package import generate_package
from braille_card.slicer import find_slicer_root, sha256_file


def test_full_package_is_byte_identical_and_path_clean(tmp_path: Path) -> None:
    repository = Path(__file__).resolve().parents[1]
    slicer_root = find_slicer_root()
    first = generate_package(
        repository / "examples/heart.svg",
        repository / "examples/card.json",
        tmp_path / "first",
        slicer_root=slicer_root,
    )
    second = generate_package(
        repository / "examples/heart.svg",
        repository / "examples/card.json",
        tmp_path / "second",
        slicer_root=slicer_root,
    )
    first_files = sorted(path.name for path in first.iterdir())
    second_files = sorted(path.name for path in second.iterdir())
    assert first_files == second_files
    assert {name: sha256_file(first / name) for name in first_files} == {
        name: sha256_file(second / name) for name in second_files
    }
    assert (first / "original_input.svg").read_bytes() == (repository / "examples/heart.svg").read_bytes()

    forbidden = [str(tmp_path), str(repository), socket.gethostname()]
    text_suffixes = {".json", ".md", ".txt", ".html", ".svg", ".brf", ".gcode"}
    for path in first.iterdir():
        if path.suffix not in text_suffixes:
            continue
        text = path.read_text(encoding="ascii" if path.suffix == ".brf" else "utf-8")
        assert all(value not in text for value in forbidden)
        assert not re.search(r"generated by OrcaSlicer .* on \d{4}-\d{2}-\d{2}", text)


def test_gcode_is_stock_sv07_profile_and_never_submitted(tmp_path: Path) -> None:
    repository = Path(__file__).resolve().parents[1]
    package = generate_package(
        repository / "examples/heart.svg",
        repository / "examples/card.json",
        tmp_path / "package",
        slicer_root=find_slicer_root(),
    )
    gcode = (package / "card.gcode").read_text(encoding="utf-8")
    assert "; printer_model = Sovol SV07" in gcode
    assert "; nozzle_diameter = 0.4" in gcode
    assert "; filament_type = PLA" in gcode
    assert "; enable_support = 1" in gcode
    assert "M140 S65" in gcode
    assert "M104 S235" in gcode
    manifest = (package / "manifest.json").read_text(encoding="utf-8")
    assert '"submitted_to_printer": false' in manifest
    assert '"print_started": false' in manifest

