#!/usr/bin/env python3
"""Regenerate the fixed, pre-generated judge-demo sample artifacts.

This produces the read-only artifacts served publicly at
braillecard.dorqlabs.com by ``braillecard-demo.service`` (see
``deploy/braillecard-demo.service`` and ``docs/JUDGE_DEMO_HOSTING.md``).
It only calls the preview stage (``generate_preview``) -- it never slices,
never contacts a printer, and never accepts an upload.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from braille_card.preview import generate_preview  # noqa: E402

# Artifacts beyond these are generated by generate_preview() but deliberately
# not published, to keep the public surface to exactly what
# docs/JUDGE_DEMO_HOSTING.md calls for.
PUBLISHED_ARTIFACTS = {
    "visual_preview.png",
    "tactile_preview.png",
    "tactile_layer.svg",
    "braille_review.html",
    "braille_source.txt",
    "braille_ueb_unicode.txt",
    "braille_ueb.brf",
}


def main() -> None:
    artifacts_dir = ROOT / "public" / "demo" / "artifacts"
    if artifacts_dir.exists():
        shutil.rmtree(artifacts_dir)
    generate_preview(ROOT / "examples" / "heart.svg", ROOT / "examples" / "card.json", artifacts_dir)

    for path in list(artifacts_dir.iterdir()):
        if path.name not in PUBLISHED_ARTIFACTS:
            path.unlink()

    missing = PUBLISHED_ARTIFACTS - {p.name for p in artifacts_dir.iterdir()}
    if missing:
        raise SystemExit(f"generate_preview did not produce expected artifacts: {sorted(missing)}")

    print(f"Wrote {len(PUBLISHED_ARTIFACTS)} judge-demo artifacts to {artifacts_dir}")


if __name__ == "__main__":
    main()
